### PR TITLE
Step 1 and step 2 of canny algorithm implementation

### LINKED ISSUE #3: załadować obrazek [pillow]

### LINKED ISSUE #11: step 1: remove the noise with gaussian filter

### LINKED ISSUE #12: step 2: find the intensity gradient of the image

### PR DESCRIPTION
**Pull request by mkuczynski11**

### CODE REVIEW

**Comment by mkuczynski11** [comment]
Since we want to implement as much functionality as we can we should consider implementing convolve function. Currently average performance of the script is around `100ms`. When we use current simplest implementation the average time is `16000ms`. This is caused by O(n^2) complexity.

NOTE: In step 1 and 2 we are using convolve 3 times and we will use it even more.

**Comment by mkuczynski11** [comment]
I think that step 1 and step 2 functions are optimal as if for now and the best way to improve them would be implementing convolve function. I found great article about how to implement it in an efficient way. Maybe it could help. https://medium.com/analytics-vidhya/implementing-convolution-without-for-loops-in-numpy-ce111322a7cd

**Comment by PiotrWolinski** [comment]
> I think that step 1 and step 2 functions are optimal as if for now and the best way to improve them would be implementing convolve function. I found great article about how to implement it in an efficient way. Maybe it could help. https://medium.com/analytics-vidhya/implementing-convolution-without-for-loops-in-numpy-ce111322a7cd

This article seems very nice and I think that it should definitely be taken into consideration while performing some optimization

**Comment by PiotrWolinski** [comment]
LGTM

**Comment by mkuczynski11** [comment]
> > I think that step 1 and step 2 functions are optimal as if for now and the best way to improve them would be implementing convolve function. I found great article about how to implement it in an efficient way. Maybe it could help. https://medium.com/analytics-vidhya/implementing-convolution-without-for-loops-in-numpy-ce111322a7cd
> 
> This article seems very nice and I think that it should definitely be taken into consideration while performing some optimization

Already submited a task to implement optimal convolve function.

**Pull request merged**
